name: 'π§ λ¦¬ν©ν† λ§ μ΄μ'
description: 'λ©ν•λƒ¥ ν΄λΌμ΄μ–ΈνΈ λ ν¬μ§€ν† λ¦¬μ— μ΄μλ¥Ό μƒμ„±ν•λ©°, Jiraμ™€ μ—°λ™λ©λ‹λ‹¤.'
labels: [refactor]
title: 'π§ μ΄μ μ λ©'
assignees:
  - octocat
body:
  - type: textarea
    id: description
    attributes:
      label: 'π“ Description'
      description: 'μ΄μμ— λ€ν•΄μ„ μƒμ„Έν μ„¤λ…ν•΄μ£Όμ„Έμ”'
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: 'β… Todo'
      description: 'ν•΄λ‹Ή μ΄μμ— λ€ν•΄ ν•„μ”ν• μ‘μ—…λ©λ΅μ„ μ‘μ„±ν•΄μ£Όμ„Έμ”'
      placeholder: '- [ ] Task1'
    validations:
      required: false